### PR TITLE
[git] Add .gitignore file

### PR DESCRIPTION
**Pull request by xqt**
Also remove python cache files and temporary dist files

Change-Id: I3243f2a0f6122226ef3b3738e2c481800f71e422

### CODE REVIEW

**Comment by TheSandDoctor** [comment]
@btubbs looks like Travis can't install python 3.7? Has this issue passed or?

**Comment by TheSandDoctor** [comment]
Just read further that it was enabled by #32 . @xqt @btubbs would it be possible to either override travis on this one or otherwise re-run the test?

**Comment by btubbs** [comment]
Yeah, merging.

**Comment by TheSandDoctor** [comment]
Thanks!!

**Pull request merged**
