### PR TITLE
do not emit comment only events

### LINKED ISSUE #41: The first event retrieved by sseclient is always empty
`
.>>> from sseclient import SSEClient
.>>> client = SSEClient(url='https://stream.wikimedia.org/v2/stream/recentchange')
.>>> data = next(client)
.>>> data.__dict__
{'data': '', 'event': 'message', 'id': None, 'retry': None}
.>>> data = next(client)
.>>> data.__dict__
{'data': '{"$schema":"/mediawiki/recentchange/1.0.0","meta":{"uri":"https://commons.wikimedia.org/wiki/File:Geschichte_des_Schultei%C3%9Fenamts_und_der_Stadt_Neumarkt_014.jpg","request_id":"Xj6I2ApAED4AADHcxFEAAABL","id":"7573678b-87b2-4325-81f8-e338613e537b","dt":"2020-02-08T10:09:30Z","domain":"commons.wikimedia.org","stream":"mediawiki.recentchange","topic":"eqiad.mediawiki.recentchange","partition":0,"offset":2157854683},"id":1327149461,"type":"log","namespace":6,"title":"File:Geschichte des Schulteißenamts und der Stadt Neumarkt 014.jpg","comment":"User created page with UploadWizard","timestamp":1581156570,"user":"DALIBRI","bot":false,"log_id":290782528,"log_type":"upload","log_action":"upload","log_params":{"img_sha1":"5oe8esm1e76smmt6zbv811c0m7ay1jo","img_timestamp":"20200208100930"},"log_action_comment":"uploaded &quot;[[File:Geschichte des Schulteißenamts und der Stadt Neumarkt 014.jpg]]&quot;: User created page with UploadWizard","server_url":"https://commons.wikimedia.org","server_name":"commons.wikimedia.org","server_script_path":"/w","wiki":"commonswiki","parsedcomment":"User created page with UploadWizard"}', 'event': 'message', 'id': '[{"topic":"eqiad.mediawiki.recentchange","partition":0,"timestamp":1581156570001},{"topic":"codfw.mediawiki.recentchange","partition":0,"offset":-1}]', 'retry': None}
>>> 
`

### PR DESCRIPTION
**Pull request by Shoelace**
added a check to not emit  events if they contain no data as per spec  on the EventSource processingmodel

resolves #41

### CODE REVIEW

**Comment by btubbs** [comment]
Can you tell me more about how wrapping it all in the `while True` is necessary?  I'm not quite following there.

**Comment by Shoelace** [comment]
__next__ is supposed to return the next event.

if an "comment only event" comes through and is then ignored.. we need to wait for the next "valid" event to return back to the iterator.

in the spec at https://www.w3.org/TR/eventsource/#event-stream-interpretation  in the example there is line that says "The first block has just a comment, and will fire nothing."
its also on the whatwg version
https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation:dom-messageevent-data-2:~:text=The%20following%20stream%20contains%20four%20blocks.%20The%20first%20block%20has%20just%20a%20comment%2C%20and%20will%20fire%20nothing

as i read it you still need to process the retry value (if provided) and set the last-id  but you only emit an event if it has data.. (the data can be just whitespace tho)

so i added a infinite loop  and do a  return only when there is data AFTER the other processing has occured

    # if data in event, emit and return
    if msg.data !='':
        return data

**Comment by TheSandDoctor** [comment]
Thank you @Shoelace !

**Comment by xqt** [comment]
@TheSandDoctor: Are you able to increase the version and bump it it pypi? This project is unmaintained for several years.

**Pull request merged**
